import jsPDF from 'jspdf'
import { gradeFromMarks, gpaFromMarks } from './utils'

type Row = { rank:number; name:string; rollNumber?:string|number; className?:string; section?:string; total:number; maxTotal:number }

export function generateMeritListPdf(rows: Row[], schoolName:string, title: string, filename='Merit-list.pdf') {
  const doc = new jsPDF({ unit:'mm', format:'a4', compress:true })
  doc.setProperties({ title:'Merit List', author:'EduSphere AI', creator:'EduSphere AI' })

  // Background
  doc.setFillColor(12,17,37); doc.rect(0,0,210,297,'F')
  // Header
  doc.setTextColor(255,255,255); doc.setFont('helvetica','bold'); doc.setFontSize(18)
  doc.text(schoolName, 105, 22, { align:'center' })
  doc.setFontSize(13); doc.setTextColor(34,211,238)
  doc.text(title.toUpperCase(), 105, 30, { align:'center' })
  doc.setDrawColor(139,92,246); doc.setLineWidth(0.5); doc.line(20, 34, 190, 34)
  doc.setFontSize(9); doc.setTextColor(180,190,220); doc.setFont('helvetica','normal')
  doc.text(`Generated by EduSphere AI on ${new Date().toLocaleDateString('en-IN')}`, 105, 40, { align:'center' })

  // Table header
  let y = 50
  doc.setFillColor(139,92,246); doc.rect(15, y-6, 180, 9, 'F')
  doc.setTextColor(255,255,255); doc.setFont('helvetica','bold'); doc.setFontSize(10)
  doc.text('Rank', 20, y); doc.text('Name', 35, y); doc.text('Roll', 110, y)
  doc.text('Class', 125, y); doc.text('Marks', 155, y, { align:'right' }); doc.text('Grade', 185, y, { align:'right' })
  y += 8

  rows.forEach((r,i) => {
    if (y > 270) { doc.addPage(); doc.setFillColor(12,17,37); doc.rect(0,0,210,297,'F'); y = 25 }
    const zebra = i%2===0
    doc.setFillColor(zebra?22:22, zebra?28:28, zebra?58:58); doc.rect(15, y-6, 180, 8, 'F')
    doc.setFont('helvetica','normal'); doc.setTextColor(230,236,255); doc.setFontSize(10)
    // Medal color for top 3
    const medalColor = r.rank===1 ? [250,204,21] : r.rank===2 ? [203,213,225] : r.rank===3 ? [180,120,60] : null
    if (medalColor) { doc.setFillColor(medalColor[0],medalColor[1],medalColor[2]); doc.circle(20,y-2,3,'F') }
    doc.setFont('helvetica','bold'); doc.setTextColor(255,255,255)
    doc.text(String(r.rank), 20, y, { align:'center' })
    doc.setFont('helvetica','normal'); doc.setTextColor(230,236,255)
    doc.text((r.name||'').substring(0,36), 35, y)
    doc.text(String(r.rollNumber||'—'), 110, y)
    doc.text(`${r.className||''}${r.section?'-'+r.section:''}`, 125, y)
    const pct = Math.round((r.total/r.maxTotal)*100)
    doc.text(`${r.total}/${r.maxTotal} (${pct}%)`, 155, y, { align:'right' })
    doc.setFont('helvetica','bold'); doc.setTextColor(34,211,238)
    doc.text(gradeFromMarks(r.total, r.maxTotal), 185, y, { align:'right' })
    y += 8
  })

  // Footer
  doc.setTextColor(150,160,190); doc.setFontSize(8); doc.setFont('helvetica','normal')
  doc.text('EduSphere AI - Crafted by Rishu Jaswar', 105, 288, { align:'center' })
  doc.save(filename)
}
